apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: miguelmartinez11/breweryserver
          env:
            - name: MONGO_URI
              value: 'mongodb+srv://cortazar11:zpCT3yYNuGipQCLr@cluster0.msz3k.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: FACEBOOK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: facebook-secret
                  key: FACEBOOK_CLIENT_KEY
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_SECRET_KEY
            - name: COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-secret
                  key: COOKIE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: server-clusterip-srv
spec:
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 5000
      targetPort: 5000
